### ISSUE TITLE
feature: button on search playground UI to "register a click", for CTR tracking

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2460]
### Description

All checkboxes below should show a popup after press where the user can specify what kind of event they want to pass that way we can differentiate between `add to cart`, `click`, and other types.

- [ ] feature: button for registering event on /scroll page
- [ ] feature: button for registering event on recommendations panel
- [ ] feature: button for registering event on RAG chat

![image](https://github.com/user-attachments/assets/7dbcb1c3-4f84-4144-a153-10c8a03ff50c)

Refer to the [analytics quickstart guide](https://docs.trieve.ai/guides/analytics-quickstart#track-click-through-rate-data) for more details on how to do this.

### Target(s)

`search`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)
