### ISSUE TITLE
tracking: pagefind local search

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2952]
### Description

- [X] Ability to push pagefind index from qdrant to s3
- [X] Ability to use `pagefind.js` to search for documents in the search component
- [x] Ability to set index filters with pagefind.js
- [x] Ability to get facets with pagefind (count's per tag)
- [x] Group search with pagefind
- [ ] Search quality testing with flagship demo
- [ ] Skip adding extra, unneeded files to index such as css files.
- [ ] Performance testing with flagship demo
   - [x] Indexing speed
   - [ ] Searching speed
 - [ ] Add pagefind to public page
 - [ ] Auto reingest

### Target(s)

`server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by saloni0419** [comment]
@cdxker @skeptrunedev can you please assign me this issue
